site_name: velenium
site_url: https://velenium.readthedocs.io/
nav:
  - Home: index.md
  - Usage: usage.md
  - Examples: examples.md

markdown_extensions:
  - toc:
      permalink: "#"
      baselevel: 2
      separator: "_"

theme: readthedocs